marker_list = struct;

sides = ["L", "R"];
marker_list.pelvis = struct( ...
    "R_ASIS", "R_ASIS", ...
    "L_ASIS", "L_ASIS", ...
    "R_PSIS", "R_PSIS", ...
    "L_PSIS", "L_PSIS" );
for i = 1:2
    si = sides(i);
    marker_list.(si+"_thigh") = struct( ...
        "V_"+ si +"_GreaterTrochanter", si+"_gt", ...
        "V_"+ si +"_LateralFemoralEpicondyle", si+"_lfe", ...
        "V_"+ si +"_MedialFemoralEpicondyle", si+"_mfe", ...
              si +"_Thigh_0", si+"_th0", ...
              si +"_Thigh_1", si+"_th1", ...
              si +"_Thigh_2", si+"_th2", ...
              si +"_Thigh_3", si+"_th3");
    marker_list.(si+"_shank") = struct(...
        "V_"+ si +"_LateralMalleolus", si+"_lm", ...
        "V_"+ si +"_MedialMalleolus", si+"_mm", ...
              si +"_Shank_0", si+"_sh0", ...
              si +"_Shank_1", si+"_sh1", ...
              si +"_Shank_2", si+"_sh2", ...
              si +"_Shank_3", si+"_sh3");
    marker_list.(si+"_foot") = struct(...
        si+"_5MT", si+"_5MT", ...
        si+"_InStep", si+"_instep", ...
        si+"_Heel", si+"_heel", ...
        "V_"+ si +"_2MT", si+"_mt2");
end

bodies = fieldnames(marker_list);
conversions = struct;
for i = 1:length(bodies) 
    
    body = bodies{i};
    inStruct = marker_list.(body);
    marks = fieldnames(marker_list.(body));
    for j = 1:length(marks)
        c3d_name = marks{j};
        conversions.(c3d_name) = inStruct.(c3d_name);
    end
end 
    
save("marker_list.mat", "marker_list", "conversions")